#include <iostream>
#include <string.h>

int main(){
std::string message = "Hello world!";
std::cout << message;
}
/* This code was generated by Applejuice's transpiler. https://github.com/Safariminer/Applejuice */