#include <raylib.h>
#include <iostream>
#include <string.h>

int main(){
InitWindow(1280, 720, "Applejuice Game");
SetTargetFPS(120);
int x = 0;
int y = 0;
std::cout << "Initialized Window and Set Up a Target FPS";
while(!WindowShouldClose()){
BeginDrawing();
ClearBackground(BLACK);
DrawText("Hello from Applejuice!", 0, 0, 10, WHITE);
if(IsKeyDown(KEY_LEFT)) x--;
if(IsKeyDown(KEY_RIGHT)) x++;
if(IsKeyDown(KEY_UP)) y--;
if(IsKeyDown(KEY_DOWN)) y++;
DrawCircle(x, y, 10, GREEN);
std::cout << "Drew Character";
EndDrawing();
}
CloseWindow();
}
/* This code was generated by Applejuice's transpiler. https://github.com/Safariminer/Applejuice */